language: node_js

node_js:
  - '18'
  - '20'
  - '22'

cache:
  directories:
    - node_modules

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+$/

stages:
  - test
  - name: release
    if: branch = main AND type = push AND commit_message !~ /\[skip ci\]/

jobs:
  include:
    # Тестирование для всех веток
    - stage: test
      name: "Lint and Test"
      node_js: '20'
      if: commit_message !~ /\[skip ci\]/
      script:
        - npm run lint
        - npm test
        - npm run build
      after_success:
        - npm install -g codecov
        - codecov
        - npm run update-badge

    # Релиз только для main ветки
    - stage: release
      name: "Create Release and Publish"
      node_js: '20'
      if: commit_message !~ /\[skip ci\]/
      script:
        - npm test
        - npm run build
      after_success:
        - npx semantic-release

notifications:
  email:
    on_success: change
    on_failure: always
